name: speed_share
description: 局域网共享文件客户终端.
publish_to: "none"

version: 2.1.5+42

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_window: ^0.2.0
  tray_manager: ^0.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  window_manager: ^0.2.3
  animations: ^2.0.2
  desktop_drop: ^0.3.3
  dio_range_download: ^1.0.1
  flutter_markdown: ^0.6.10+2
  clipboard_watcher: ^0.1.2
  # 文件选择自实现方案
  file_selector_nightmare:
    git: https://github.com/nightmare-space/file_selector_meng
  signale: ^0.0.7
  file_manager_view:
    git: https://github.com/nightmare-space/file_manager_view.git
  file_selector: ^0.8.4+2
  get: ^4.1.3
  # 公共库
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  #动画组件
  simple_animations: ^2.4.0
  logger_view:
    git: https://github.com/nightmare-space/logger_view
  # 二维码生成
  qr_flutter: ^4.0.0
  open_file: ^3.2.1
  # scan qr code
  mobile_scanner: ^2.0.0
  # 文件部署
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  shelf_proxy: ^1.0.0
  shelf_static:
    git:
      url: https://github.com/nightmare-space/shelf
      path: pkgs/shelf_static
  # video preview
  better_player: ^0.0.83
  # 聊天服务器
  get_server: ^1.1.0
  # 安卓端文件选择
  file_picker: ^3.0.1
  # svg 图片展示
  flutter_svg: ^0.22.0
  # 跳转网页
  url_launcher: ^6.0.4
  # 压缩插件
  archive: ^3.1.2
  path: ^1.8.0
  # 获取文件对应的 mime_type 用的库
  mime_type: ^1.0.0
  # 网络请求
  dio: ^4.0.0
  responsive_framework: ^0.2.0
  # 局域网设备发现
  multicast:
    git: https://github.com/nightmare-space/multicast
  app_manager:
    git: https://github.com/nightmare-space/app_manager
  image_picker: ^0.8.5
  settings:
    git: https://github.com/nightmare-space/settings
  path_provider: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  # fonts:
  #   - family: MiSans
  #     fonts:
  #       - asset: assets/fonts/MiSans-Medium.ttf
  #       - asset: assets/fonts/MiSans-Bold.ttf
  #         weight: 700
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/

dependency_overrides:
  flutter_svg: ^1.1.0
  xterm:
    git:
      url: https://github.com/TerminalStudio/xterm.dart
  # android_window:
  #   path: /Users/didi/Documents/GitHub/flutter-android-window
  # xterm: ^3.2.6
  logger_view:
    path: ../logger_view
  # app_manager:
  #   path: ../app_manager
  # applib_util:
  #   path: ../applib/applib_util
  # global_repository:
  #   path: ../global_repository
  # file_manager_view:
  #   path: ../file_manager_view
  # file_selector_nightmare:
  #   path: /Users/nightmare/Desktop/nightmare-space/file_selector_meng
  # user_center_frontend:
  #   path: ../user_center_frontend
flutter_intl:
  enabled: true
