name: speed_share
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  simple_animations: ^2.4.0
  shelf_proxy: ^1.0.0
  qr_flutter: ^3.1.0
  shelf_static: ^1.0.0
  get_server: ^1.1.0
  getsocket: ^1.0.0
  permission_handler: ^8.0.0+1
  file_picker: ^3.0.1
  file_manager:
    git: https://github.com/nightmare-space/file_manager
  url_launcher: ^6.0.4
  flick_video_player: ^0.3.1
  video_viewer: ^1.2.2
  better_player: ^0.0.68
  video_compress: ^2.1.0
  archive: ^3.1.2
  path: ^1.8.0
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
