name: speed_share
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  simple_animations: ^2.4.0
  http_server: ^0.9.8+3
  shelf_proxy: ^0.1.0+7
  qr_flutter: ^3.1.0
  shelf_static: ^0.2.9+2

  permission_handler: 5.0.1+1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
