name: speed_share
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  simple_animations: ^2.4.0
  shelf_proxy: ^0.1.0+7
  qr_flutter: ^3.1.0
  shelf_static: ^0.2.9+2
  get_server: ^1.1.0
  getsocket: ^1.0.0
  permission_handler: ^8.0.0+1
  file_picker: ^3.0.1
  file_manager:
    path: ../file_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
